### PR TITLE
fix unset/cleanup "nss_wrapper" bits

### LINKED ISSUE #918: [has fix] PR #888 is incomplete
## issue
PR #888 introduced an approach to find the _libnss_library: https://github.com/infosiftr/postgres/blob/ab940cbb923af99e2c7cf0e0ba5305bc6815aecc/docker-entrypoint.sh#L73-L84

This approach was invalid because it used the pattern `{/usr,}/lib{/*,}/libnss_wrapper.so`. Depending on environment, it might find binaries in
```
/usr/lib/x86_64-linux-gnu/libnss_wrapper.so
/usr/lib/libnss_wrapper.so
/lib/*/libnss_wrapper.so
/lib/libnss_wrapper.so
```

Later in the code, "nss_wrapper" bits get unset/cleanup, but `LD_PRELOAD` is tested against `/usr/lib/libnss_wrapper.so` only. So in worst-cast, the variables won't get unset: https://github.com/infosiftr/postgres/blob/ab940cbb923af99e2c7cf0e0ba5305bc6815aecc/docker-entrypoint.sh#L94

## fix
https://github.com/docker-library/postgres/pull/919

## hint
There might be better approaches, f.e. testing if `LD_PRELOAD` has been set at all or making it POSIX-compatible, but I wanted to keep most of the original code.

### PR DESCRIPTION
**Pull request by tobwen**
original code didn't respect libnss-wrapper at other locations

fixes #918

### CODE REVIEW

File: docker-entrypoint.sh [hunk 1]
```diff
@@ -91,7 +91,7 @@ docker_init_database_dir() {
 	eval 'initdb --username="$POSTGRES_USER" --pwfile=<(echo "$POSTGRES_PASSWORD") '"$POSTGRES_INITDB_ARGS"' "$@"'
 
 	# unset/cleanup "nss_wrapper" bits
-	if [ "${LD_PRELOAD:-}" = '/usr/lib/libnss_wrapper.so' ]; then
+	if [ "${LD_PRELOAD:-}" = "$wrapper" ]; then
```
Comment (tianon) [inline docker-entrypoint.sh:94]: Ah, great catch -- however, `wrapper` is only set conditionally above, so I think this fix needs to be a little more advanced.  We probably need to move `local wrapper` outside the `if` statement, and probably explicitly set it to the empty string (`local wrapper=''`) so that we can detect it appropriately down here:

```suggestion
	if [ -n "$wrapper" ] && [ -s "$wrapper" ] && [ "${LD_PRELOAD:-}" = "$wrapper" ]; then
```

Comment (tobwen) [reply docker-entrypoint.sh:94]: Actually,  it might even be easier then (since LD_PRELOAD should be empty anyway and we're unsetting it afterwards)
``` bash
if [ "w${LD_PRELOAD}" != "w" ]; then
```
or even simpler:
``` bash
if [ "${LD_PRELOAD}" != "" ]; then
```
or POSIX - the best in my opinion:
``` bash
case "$LD_PRELOAD" in %libnss_wrapper.so)
	# do stuff
	;;
esac
```

Comment (tianon) [reply docker-entrypoint.sh:94]: Ah, good point -- however, this script is already Bash (and uses several bashisms), so something like this is probably the simplest option:

```suggestion
	if [[ "${LD_PRELOAD:-}" == */libnss_wrapper.so ]]; then
```

We could go overboard and also check for the two variables we immediately use being set as well, but I don't think that's really strictly necessary.

Comment (tobwen) [reply docker-entrypoint.sh]: Okay, I've updated it.

**Comment by tianon** [comment]
Nice, thank you!
